### ISSUE TITLE
Doc: Reimplement cross-docs links after initial target files for snmp are generated

### ISSUE THREAD

**Issue by karenzone** [logstash-plugins/logstash-integration-snmp#3]
Related issue: #2
Related PR: 
* #1
* #56 
* #60

We can't create files and link to the generated output of those files in the same PR. We removed some headers and cross-docs in preparation for the initial merge and publish (#1).  

### Backstory
> "These links should be removed for the initial commit. Why?
The generated files were targeting don't exist yet. (We're merging the original source files as part of this PR.) We can't link to those generated files until they've been created, merged, published, and generated. Linking to non-existent files will break docs-ci, and if merged, will break the entire docs build."

This issue tracks reimplementing headers and links after target files have been generated and merged. 

## ToDo
- [x] Search and fix instances in which we've commented out links to generated files--plugin headers, for example.
    * Example: https://github.com/logstash-plugins/logstash-integration-snmp/pull/1#discussion_r1486762407
- [x] Search and fix instances in which we've hard coded plugin names to remove offending links. 
- [x] Implement a link in plugin "migration" banners to migration section in imtegration index page. 
    Related: #15
- [x] Next round: Add links to MIBs after first round of generated content is merged: #60

**Comment by karenzone** [comment]
Final fixes:
- [ ] https://github.com/elastic/logstash-docs/pull/1677
- [ ] https://github.com/elastic/logstash-docs/pull/1675
